### PR TITLE
CAN1-48 Added Acceptance Filter Requirement

### PR DESCRIPTION
**Pull request by hruy1**

### CODE REVIEW

**Comment by PricelessAntonio** [comment]
Address the following comments within the uploaded doc.
[Acceptance Filter Requirement Comments v1.docx](https://github.com/hruy1/CAN_we_do_it_Can_Controller/files/4920660/Acceptance.Filter.Requirement.Comments.v1.docx)
[Acceptance Filter Requirements Checklist v1.docx](https://github.com/hruy1/CAN_we_do_it_Can_Controller/files/4920661/Acceptance.Filter.Requirements.Checklist.v1.docx)

**Review by PricelessAntonio — DISMISSED** [review]
Address the comments in the uploaded document.

**Comment by djstedronsky** [comment]
Comments in document and checklist.

[Acceptance Filter Requirement Comments Rev 1.docx](https://github.com/hruy1/CAN_we_do_it_Can_Controller/files/4933305/Acceptance.Filter.Requirement.Comments.Rev.1.docx)
[Acceptance Filter Requirements Review Rev 1.docx](https://github.com/hruy1/CAN_we_do_it_Can_Controller/files/4933306/Acceptance.Filter.Requirements.Review.Rev.1.docx)

**Comment by djstedronsky** [comment]
[acceptance_filter_review_rev2.docx](https://github.com/hruy1/CAN_we_do_it_Can_Controller/files/4939775/acceptance_filter_review_rev2.docx)
[Acceptance_Filter_Requirement_comments_rev2.docx](https://github.com/hruy1/CAN_we_do_it_Can_Controller/files/4939776/Acceptance_Filter_Requirement_comments_rev2.docx)

Almost there. Specify signal name for internal state in AF_AFR_6-10. Specify the usage of the register values so that they can be verified in AF_AFR_2-5.

**Comment by djstedronsky** [comment]
AF_AFR_2-9 : Need to specify what 'passing' means. ex. AF_AFR_2 If ‘i_uaf1’ is set to 1 and input data ‘i_rx_message[127:96]’ **is equal to the corresponding bits** in AFR1, internal signal ‘in_pass1’ shall be set to 1.

**Review by djstedronsky — APPROVED** [review]

**Pull request merged**
